name: rspec

on: [push, pull_request]

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: "postgres"
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up ruby and restore/install gem dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.3
          bundler-cache: true
      - name: Restore node dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}  
      - name: Install node dependencies
        run: yarn install --frozen-lockfile
      - name: Create database
        run: RAILS_ENV=test bundle exec rails db:create
      - name: Run tests
        run: bundle exec rspec
